name: Pipeline
on: [push, pull_request]

jobs:
  build-assignments:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blackbrad/aoc2023:v3
      volumes:
        - ${{ github.workspace }}:/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}
    steps:
    - uses: actions/checkout@v3
    - run: /inside.sh build

  build-unit-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blackbrad/aoc2023:v3
      volumes:
        - ${{ github.workspace }}:/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v3
      # Ignore warnings about dubious errors when updating submodules
      - run: /inside.sh test

  build-examples:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blackbrad/aoc2023:v3
      volumes:
        - ${{ github.workspace }}:/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v3
      - run: /inside.sh examples

  run-integration-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blackbrad/aoc2023:v3
      volumes:
        - ${{ github.workspace }}:/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v3
      - run: /inside.sh build
      - run: bash ./github/run_integration_tests.sh
