name: Pipeline
on: [push, pull_request]

jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blackbrad/aoc2023:v3
      volumes:
        - ${{ github.worspace}}:/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.TOKEN_GITHUB }}
      steps:
        - uses: actions/checkout@v3
        - run: inside.sh examples

  build-days:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blackbrad/aoc2023:v3
      volumes:
        - ${{ github.worspace}}:/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.TOKEN_GITHUB }}
      steps:
        - uses: actions/checkout@v3
        - run: inside.sh build

  build-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blackbrad/aoc2023:v3
      volumes:
        - ${{ github.worspace}}:/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.TOKEN_GITHUB }}
      steps:
        - uses: actions/checkout@v3
        - run: inside.sh tests
